# Generated by Django 5.2.1 on 2025-05-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='children',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.parentprofile'),
            preserve_default=False,
        ),
    ]
