# Generated by Django 5.2.1 on 2025-05-13 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studentprofile_guardian_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='phone_number',
            field=models.CharField(default='07066623544', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parentprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
