# Generated by Django 5.2.1 on 2025-05-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_parentprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('sms', 'SMS')], max_length=20),
        ),
    ]
