# Generated by Django 5.2.1 on 2025-05-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=10),
            preserve_default=False,
        ),
    ]
