# Generated by Django 5.2.1 on 2025-05-14 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_studentprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 5, 5)),
        ),
    ]
