# Generated by Django 5.2.1 on 2025-05-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_studentprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(default='Nigeria', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='state',
            field=models.CharField(default='Lagos', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
