# Generated by Django 5.2.1 on 2025-05-24 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_communicationrecipient_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationtargetgroup',
            name='class_name',
        ),
        migrations.AddField(
            model_name='communicationtargetgroup',
            name='class_arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classarm'),
        ),
        migrations.AddField(
            model_name='communicationtargetgroup',
            name='non_teaching_positions',
            field=models.ManyToManyField(blank=True, to='accounts.nonteachingposition'),
        ),
        migrations.AddField(
            model_name='communicationtargetgroup',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('teaching', 'Teaching Staff'), ('non_teaching', 'Non-Teaching Staff'), ('both', 'Teaching and Non-Teaching Staff')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='communicationtargetgroup',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentclass'),
        ),
        migrations.AddField(
            model_name='communicationtargetgroup',
            name='teaching_positions',
            field=models.ManyToManyField(blank=True, to='accounts.teachingposition'),
        ),
        migrations.AlterField(
            model_name='communicationtargetgroup',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('branch_admin', 'Branch Admin'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], max_length=20, null=True),
        ),
    ]
