# Generated by Django 5.2.1 on 2025-05-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_communicationtargetgroup_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='send_to_all',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
