# Generated by Django 5.2.1 on 2025-06-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_communication_send_to_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtargetgroup',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('branch_admin', 'Branch Admin'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, max_length=20, null=True),
        ),
    ]
