# Generated by Django 5.2.1 on 2025-06-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_communicationtargetgroup_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationrecipient',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationrecipient',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationrecipient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='communicationattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='communication_attachments/'),
        ),
    ]
