# Generated by Django 5.2.1 on 2025-06-03 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_communication_sent_communicationrecipient_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationrecipient',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_communications', to=settings.AUTH_USER_MODEL),
        ),
    ]
