# Generated by Django 5.2.1 on 2025-06-04 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_communicationrecipient_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtargetgroup',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
            preserve_default=False,
        ),
    ]
