# Generated by Django 5.2.1 on 2025-06-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_communicationtargetgroup_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingposition',
            name='is_class_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
