# Generated by Django 5.2.1 on 2025-06-06 05:45

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_staffprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentprofile',
            options={'ordering': ['user__last_name'], 'verbose_name': 'Parent Profile', 'verbose_name_plural': 'Parent Profiles'},
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='parent_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('sms', 'SMS')], default='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
