# Generated by Django 5.2.1 on 2025-06-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_parentprofile_options_parentprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['staff', 'superadmin', 'branch_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
