# Generated by Django 5.2.1 on 2025-06-06 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_staffprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teachingposition'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='relationship_to_student',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], default='father', max_length=20, verbose_name='Relationship to Student'),
        ),
    ]
