# Generated by Django 5.2.1 on 2025-06-15 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_staffprofile_position_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='position',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='position_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'accounts'), ('model__in', ['teachingposition', 'nonteachingposition'])), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='position_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
