# Generated by Django 5.2.1 on 2025-06-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_staffprofile_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
