# Generated by Django 5.2.1 on 2025-06-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_communication_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='manual_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='communication',
            name='selected_recipient_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
