# Generated by Django 5.2.1 on 2025-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_communication_manual_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='requires_response',
            field=models.BooleanField(default=False),
        ),
    ]
