# Generated by Django 5.2.1 on 2025-06-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_communication_requires_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationrecipient',
            name='has_responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationrecipient',
            name='requires_response',
            field=models.BooleanField(default=False),
        ),
    ]
