# Generated by Django 5.2.1 on 2025-06-19 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_communicationrecipient_has_responded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('replied_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.communicationrecipient')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
