# Generated by Django 5.2.1 on 2025-06-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_messagereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereply',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reply_attachments/'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['sender', 'is_draft'], name='accounts_co_sender__24e023_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['sent', 'scheduled_time'], name='accounts_co_sent_995728_idx'),
        ),
    ]
