# Generated by Django 5.2.1 on 2025-06-20 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_messagereply_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagereply',
            name='file',
        ),
        migrations.CreateModel(
            name='ReplyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reply_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.messagereply')),
            ],
        ),
    ]
