# Generated by Django 5.2.1 on 2025-06-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_messagereply_file_replyattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='saved_filter_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
