# Generated by Django 5.2.1 on 2025-05-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_staffprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', help_text='Upload a profile picture.', null=True, upload_to='profile_pictures/'),
        ),
    ]
