# Generated by Django 5.2.1 on 2025-05-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', help_text='Upload a profile picture.', null=True, upload_to='profile_pictures/'),
        ),
    ]
